name = "kikaku-server"
author = "ryo-server-developer"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a887a447efce350add90e9ed57ab4cbc6330056c18acba810ca3321d96bf3b8d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
