name = "kikaku-server"
author = "ryo-server-developer"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e1f66a71bb133d5f13b166699c8428152af9b436b028ea06da30316570de93e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
