name = "kikaku-server"
author = "ryo-server-developer"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb244ae206b54ef2d6c988f5da806a1652a9792ac3f6cf3f556a70dce49e1931"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
